// <auto-generated />
using System;
using LibraryManagement.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LibraryManagement.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260312071108_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LibraryManagement.Models.Book", b =>
                {
                    b.Property<int>("BookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookId"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ISBN")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime>("PublishedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BookId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            BookId = 1,
                            Author = "Robert C. Martin",
                            Description = "A handbook of agile software craftsmanship.",
                            Genre = "Programming",
                            ISBN = "978-0132350884",
                            IsAvailable = true,
                            Price = 35.99m,
                            PublishedDate = new DateTime(2008, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Code"
                        },
                        new
                        {
                            BookId = 2,
                            Author = "Andrew Hunt",
                            Description = "Your journey to mastery.",
                            Genre = "Programming",
                            ISBN = "978-0135957059",
                            IsAvailable = true,
                            Price = 49.99m,
                            PublishedDate = new DateTime(2019, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Pragmatic Programmer"
                        },
                        new
                        {
                            BookId = 3,
                            Author = "Gang of Four",
                            Description = "Elements of reusable object-oriented software.",
                            Genre = "Software Architecture",
                            ISBN = "978-0201633610",
                            IsAvailable = false,
                            Price = 54.99m,
                            PublishedDate = new DateTime(1994, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Design Patterns"
                        },
                        new
                        {
                            BookId = 4,
                            Author = "Jon Skeet",
                            Description = "A deep dive into the C# language.",
                            Genre = "Programming",
                            ISBN = "978-1617294532",
                            IsAvailable = true,
                            Price = 44.99m,
                            PublishedDate = new DateTime(2019, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "C# in Depth"
                        },
                        new
                        {
                            BookId = 5,
                            Author = "Andrew Lock",
                            Description = "Build cross-platform web apps with ASP.NET Core.",
                            Genre = "Web Development",
                            ISBN = "978-1617298301",
                            IsAvailable = true,
                            Price = 59.99m,
                            PublishedDate = new DateTime(2021, 6, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ASP.NET Core in Action"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
